# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0154c9e29ff350cfea0c85f11e8a78a328ccc0d1d1aa5ef82d34d56efc72d1875252bd69e0102c1adeb40b2dbb627e41610c48c405cd84708ee58257eb7b85c

test:
  secret_key_base: c76275e49acfc3bc314bcf5b4d9fe3c11e4bd9a63844fbac6162b2c772b326e5b6f6b68307d2b9eb0f6a47689cb44fd3ce01d42c9c938d625477b920c8763173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
